TradeSystem:
  Prefix: "&8[&cTrade&8] &r"
  Language: ENG
  # Permissions:
  #   "tradesystem.trade": Can accept/deny/toggle trade requests
  #   "tradesystem.trade.initiate": Can invite players for trades
  # If permissions are disabled, every player is able to accept/deny/toggle/initiate trades
  Permissions: true
  # Only set this to 'true' if you're using TradeProxy. Otherwise, you'll be vulnerable to dupes caused by custom payload attacks.
  TradeProxy: false

  # Both traders have to add an item/money to finish the trade
  Trade_Both: true
  # The GUI type which will be used to enter the money amount. Available options: SIGN, ANVIL
  Input_GUI: ANVIL
  Trade_Distance:
    enabled: true
    distance_in_blocks: 50

  # This is highly recommended to be enabled. Otherwise, players can easily scam others. Only disable this setting if you know your users.
  Revoke_Ready_State_on_Offer_Change: true

  Allowed_GameModes:
  - SURVIVAL
  Blocked_Worlds:
  - "ExampleWorld-1"
  - "ExampleWorld-2"

  Allowed_Regions:
    # Valid modes: Blacklist, Whitelist
    # Blacklist: All regions are allowed except the ones in the list
    # Whitelist: Only the regions in the list are allowed
    Mode: Blacklist
    Regions: []

  # Example:            (all variables are optional)
  # - Material: STONE
  #   Data: 0
  #   DisplayName: 0
  #   Lore: "Some text that will be searched in every line."
  #   CustomModelData: 0
  #   Compare: IGNORE_CASE      (Default=IGNORE_CASE; STRICT, IGNORE_CASE, CONTAINS, CONTAINS_IGNORE_CASE, REGEX_ANY, REGEX_ALL)
  # 
  # Compare examples
  #   STRICT: "FOO" = "FOO"
  #   IGNORE_CASE: "FOO" = "foo"
  #   CONTAINS: "F" is in "Foo"
  #   CONTAINS_IGNORE_CASE: "f" is in "Foo"
  #   REGEX_ANY: "." matches "Foo"
  #   REGEX_ALL: ".*" matches "Foo"
  Blacklist: []

  Trade_Countdown:
    Enabled: true
    # in ticks (20 ticks = 1 second)
    Interval: 20
    Repetitions: 3

  # true: After finishing a trade all overflowing items will be dropped, if the inventory is full
  # false: Prevent the trade partner to put too many items into the gui. Also prevents a trading player from picking up items.
  Trade_Drop_Items: true

  # In seconds (e.g. after <60> seconds the request will be expired)
  Trade_Request_Expiration_Time: 60

  # The report shows what was traded during a trade.
  Trade_Finish_Report:
    Items: true
    # Whether to only display an item's name rather than item type and name
    Display_Name_Only: false
    Economy: true

  Action_To_Cancel:
    Player_get_damaged: true
  Action_To_Request:
    Shift_Rightclick: true

  Money:
    # This pattern will be used to enter money in the trade GUI and to display the current amount. More information about pattern can be found here: https://docs.oracle.com/javase/tutorial/i18n/format/decimalFormat.html
    Pattern: "###,###.####"
    Grouping_Separator: ','
    Decimal_Separator: '.'

    Easy_Selection:
      Enabled: true
      # Do NOT use special symbols (e.g. '$') here.
      # Use characters only!
      Shortcuts:
      - Keys:
          - "k"
        Value: 1000
      - Keys:
          - "m"
          - "mio"
        Value: 1000000

  # Warning: The aliases will not be validated. Make sure they are correct.
  Commands:
    Trade:
    - trade
    Accept:
    - accept
    Deny:
    - deny
    Toggle:
    - toggle

  Database:
    # Values: SQLite, MySQL
    Type: SQLite
    MySQL:
      Connection_URL: "jdbc:mysql://localhost:3306/tradesystem?autoReconnect=true&useSSL=false"
      User: root
      Password: password

  TradeLog:
    # The bukkit logger works additionally to the database logging.
    Bukkit_logger: false

  # Sound names can be found here: https://github.com/CodingAir/CodingAPI/tree/master/src/main/java/de/codingair/codingapi/server/sounds/Sound.java
  Sounds:
    Trade_Started:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Finished:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Blocked:
      Name: NOTE_BASS
      Volume: 0.8
      Pitch: 0.6
    Trade_Cancelled:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0
    Trade_Request:
      Name: ORB_PICKUP
      Volume: 0.6
      Pitch: 1.0
    Countdown_Tick:
      Name: ORB_PICKUP
      Volume: 0.6
      Pitch: 1.0
    Countdown_Stop:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0
    Change_during_Shulker_Peek:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0