TradeSystem:
  Request_Cooldown_In_Sek: 60
  Trade_with_money: true
  Trade_Distance:
    enabled: true
    distance_in_blocks: 50
  Action_To_Cancel:
    Player_get_damaged: true
  Action_To_Request:
    Rightclick: false
    Shiftclick: true
  Allowed_GameModes:
  - SURVIVAL